### ISSUE TITLE
landscap view issue

### ISSUE THREAD

**Issue by Vasantika20** [Jackiu1997/flutter_camera#1]
Its not showing properly in landscap mode.  Please help me top resolve this issue. I need to display landscap camera only.

**Comment by Jackiu1997** [comment]
what do you mean about landscape mode, the app can take landscape mode photo, it is just has no rotate camera page icons, so it can not feel, it is landscape mode.

**Comment by Vasantika20** [comment]
![Screenshot_20200228-125314](https://user-images.githubusercontent.com/52956589/75519641-b2507e00-5a29-11ea-9903-128c024831cc.png)

Please check in attached screenshot, when i check in landscape mode camera preview is not proper(rotated 90 degrees).  And also not showing in fullscreen mode.

**Comment by Jackiu1997** [comment]
I did not create the landscape mode capture, so it is rotated by flutter system, if you want to have a better performance, you can fix horizontal screen before runapp function, and write icon rotate code to show screen state, this is better.

**Comment by Vasantika20** [comment]
I have tried with fix landscape mode before runApp() , but still the same result. This issue coming from camera plugin. Please help me if you have any idea about it.

**Comment by Jackiu1997** [comment]
Did you try to lock phone roation?When I try it on my phone, the preview is not transfromed.

**Comment by Vasantika20** [comment]
Yes, phone rotation is locked...Did you mean fix the orientation to portrait programmatically? Then check in landscape device?

**Comment by Jackiu1997** [comment]
I mean that fix orientaion on the phone first

**Comment by Vasantika20** [comment]
I tried both the cases, still not working. can you please share screenshot, so that i get better idea.

**Comment by Jackiu1997** [comment]
ok, i am installing the app, please wait a second.

**Comment by Jackiu1997** [comment]
![Screenshot_2020-02-28-19-50-47-740_com example fl](https://user-images.githubusercontent.com/30568773/75546642-f496b100-5a63-11ea-8fca-5a98d59e0a14.jpg)

This is I open the phone oriention, the locked portrait in the program, the photo is normal.

**Comment by Jackiu1997** [comment]
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:camera/camera.dart';
import 'package:path_provider/path_provider.dart';

import 'package:flutter_camera/tools/photo_tools.dart';
import 'package:flutter_camera/pages/album_page.dart';

/// 相机主页面
///
///   用于进行照相操作，采用 camera 获取相机流数据
///
class CameraPage extends StatefulWidget {
  final List<CameraDescription> cameras;

  CameraPage(this.cameras, {Key key}) : super(key: key);

  @override
  _CameraPageState createState() => _CameraPageState();
}

class _CameraPageState extends State<CameraPage> {
  CameraController controller;
  int nowCamera = 1;

  @override
  void initState() {
    super.initState();

    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);

    _onButtonChangeCameraPressed();
    checkNotInDBPhotos();
  }

  @override
  void dispose() {
    controller?.dispose();

    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight,
    ]);

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      child: Scaffold(
        body: Stack(
          alignment: Alignment.center,
          fit: StackFit.expand,
          children: <Widget>[
            Container(
              color: Colors.black,
              child: _cameraPreViewWidget(),
            ),
            Positioned(
              bottom: 18.0,
              child: _bottomBarWidget(),
            ),
          ],
        ),
      ),
      onWillPop: () {
        SystemNavigator.pop();
      },
    );
  }

  Widget _buildPortraitScreen() {
    return Stack(
      alignment: Alignment.center,
      fit: StackFit.expand,
      children: <Widget>[
        Container(
          color: Colors.black,
          child: _cameraPreViewWidget(),
        ),
        Positioned(
          bottom: 18.0,
          child: _bottomBarWidget(),
        ),
      ],
    );
  }

  Widget _buildLandscapeScreen() {
    return Stack(
      alignment: Alignment.center,
      fit: StackFit.expand,
      children: <Widget>[
        Container(
          color: Colors.black,
          child: RotatedBox(
            quarterTurns: 1,
            child: _cameraPreViewWidget(),
          ),
        ),
        Positioned(
          right: 18.0,
          child: _bottomBarWidget(),
        ),
      ],
    );
  }

  /// 子 Widget 定义
  ///
  /// 相机预览 Widget
  Widget _cameraPreViewWidget() {
    return Center(
      child: !controller.value.isInitialized
          ? null
          : AspectRatio(
              aspectRatio: controller.value.aspectRatio,
              child: CameraPreview(controller),
            ),
    );
  }

  /// 页面底部按钮 Widget
  Widget _bottomBarWidget() {
    return SizedBox(
      width: 300,
      height: 90,
      child: Row(
        children: <Widget>[
          Expanded(
            flex: 1,
            child: FloatingActionButton(
              heroTag: "btn1",
              child: Icon(Icons.photo),
              backgroundColor: Color(0x50FFFFFF),
              onPressed: _onButtonOpenAlbumPressed,
            ),
          ),
          Expanded(
            flex: 1,
            child: FloatingActionButton(
              heroTag: "btn2",
              child: Icon(Icons.camera),
              backgroundColor: Color(0x50FFFFFF),
              onPressed: _onButtonTakePhotoPressed,
            ),
          ),
          Expanded(
            flex: 1,
            child: FloatingActionButton(
              heroTag: "btn3",
              child: nowCamera == 0
                  ? Icon(Icons.camera_rear)
                  : Icon(Icons.camera_front),
              backgroundColor: Color(0x50FFFFFF),
              onPressed: _onButtonChangeCameraPressed,
            ),
          ),
        ],
      ),
    );
  }

  /// 按钮事件响应
  ///
  /// 进入相册按钮响应
  void _onButtonOpenAlbumPressed() async {
    Navigator.push(
        context, MaterialPageRoute(builder: (context) => AlbumPage()));
  }

  /// 拍照按钮响应
  void _onButtonTakePhotoPressed() async {
    if (!controller.value.isInitialized) {
      return null;
    }
    final Directory extDir = await getApplicationDocumentsDirectory();
    final String dirPath = '${extDir.path}/Pictures';
    await Directory(dirPath).create(recursive: true);
    final String filePath = '$dirPath/IMG_${timestamp()}.jpg';

    if (controller.value.isTakingPicture) {
      return null;
    }
    await controller.takePicture(filePath);
    createPhotoData(filePath);
  }

  /// 转换摄像头按钮响应
  void _onButtonChangeCameraPressed() async {
    nowCamera = nowCamera == 0 ? 1 : 0;
    CameraDescription cameraDescription = widget.cameras[nowCamera];
    if (controller != null) {
      await controller.dispose();
    }
    controller = CameraController(cameraDescription, ResolutionPreset.high);
    controller.addListener(() {
      if (mounted) setState(() {});
    });
    await controller.initialize();
    if (mounted) setState(() {});
  }

  /// 生成当前时间戳，用作相片名称一部分
  String timestamp() => DateTime.now().millisecondsSinceEpoch.toString();
}

**Comment by Jackiu1997** [comment]
> these is the camera_page.dart

``` Dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:camera/camera.dart';
import 'package:path_provider/path_provider.dart';

import 'package:flutter_camera/tools/photo_tools.dart';
import 'package:flutter_camera/pages/album_page.dart';

/// 相机主页面
///
///   用于进行照相操作，采用 camera 获取相机流数据
///
class CameraPage extends StatefulWidget {
  final List<CameraDescription> cameras;

  CameraPage(this.cameras, {Key key}) : super(key: key);

  @override
  _CameraPageState createState() => _CameraPageState();
}

class _CameraPageState extends State<CameraPage> {
  CameraController controller;
  int nowCamera = 1;

  @override
  void initState() {
    super.initState();

    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);

    _onButtonChangeCameraPressed();
    checkNotInDBPhotos();
  }

  @override
  void dispose() {
    controller?.dispose();

    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight,
    ]);

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      child: Scaffold(
        body: Stack(
          alignment: Alignment.center,
          fit: StackFit.expand,
          children: <Widget>[
            Container(
              color: Colors.black,
              child: _cameraPreViewWidget(),
            ),
            Positioned(
              bottom: 18.0,
              child: _bottomBarWidget(),
            ),
          ],
        ),
      ),
      onWillPop: () {
        SystemNavigator.pop();
      },
    );
  }

  Widget _buildPortraitScreen() {
    return Stack(
      alignment: Alignment.center,
      fit: StackFit.expand,
      children: <Widget>[
        Container(
          color: Colors.black,
          child: _cameraPreViewWidget(),
        ),
        Positioned(
          bottom: 18.0,
          child: _bottomBarWidget(),
        ),
      ],
    );
  }

  Widget _buildLandscapeScreen() {
    return Stack(
      alignment: Alignment.center,
      fit: StackFit.expand,
      children: <Widget>[
        Container(
          color: Colors.black,
          child: RotatedBox(
            quarterTurns: 1,
            child: _cameraPreViewWidget(),
          ),
        ),
        Positioned(
          right: 18.0,
          child: _bottomBarWidget(),
        ),
      ],
    );
  }

  /// 子 Widget 定义
  ///
  /// 相机预览 Widget
  Widget _cameraPreViewWidget() {
    return Center(
      child: !controller.value.isInitialized
          ? null
          : AspectRatio(
              aspectRatio: controller.value.aspectRatio,
              child: CameraPreview(controller),
            ),
    );
  }

  /// 页面底部按钮 Widget
  Widget _bottomBarWidget() {
    return SizedBox(
      width: 300,
      height: 90,
      child: Row(
        children: <Widget>[
          Expanded(
            flex: 1,
            child: FloatingActionButton(
              heroTag: "btn1",
              child: Icon(Icons.photo),
              backgroundColor: Color(0x50FFFFFF),
              onPressed: _onButtonOpenAlbumPressed,
            ),
          ),
          Expanded(
            flex: 1,
            child: FloatingActionButton(
              heroTag: "btn2",
              child: Icon(Icons.camera),
              backgroundColor: Color(0x50FFFFFF),
              onPressed: _onButtonTakePhotoPressed,
            ),
          ),
          Expanded(
            flex: 1,
            child: FloatingActionButton(
              heroTag: "btn3",
              child: nowCamera == 0
                  ? Icon(Icons.camera_rear)
                  : Icon(Icons.camera_front),
              backgroundColor: Color(0x50FFFFFF),
              onPressed: _onButtonChangeCameraPressed,
            ),
          ),
        ],
      ),
    );
  }

  /// 按钮事件响应
  ///
  /// 进入相册按钮响应
  void _onButtonOpenAlbumPressed() async {
    Navigator.push(
        context, MaterialPageRoute(builder: (context) => AlbumPage()));
  }

  /// 拍照按钮响应
  void _onButtonTakePhotoPressed() async {
    if (!controller.value.isInitialized) {
      return null;
    }
    final Directory extDir = await getApplicationDocumentsDirectory();
    final String dirPath = '${extDir.path}/Pictures';
    await Directory(dirPath).create(recursive: true);
    final String filePath = '$dirPath/IMG_${timestamp()}.jpg';

    if (controller.value.isTakingPicture) {
      return null;
    }
    await controller.takePicture(filePath);
    createPhotoData(filePath);
  }

  /// 转换摄像头按钮响应
  void _onButtonChangeCameraPressed() async {
    nowCamera = nowCamera == 0 ? 1 : 0;
    CameraDescription cameraDescription = widget.cameras[nowCamera];
    if (controller != null) {
      await controller.dispose();
    }
    controller = CameraController(cameraDescription, ResolutionPreset.high);
    controller.addListener(() {
      if (mounted) setState(() {});
    });
    await controller.initialize();
    if (mounted) setState(() {});
  }

  /// 生成当前时间戳，用作相片名称一部分
  String timestamp() => DateTime.now().millisecondsSinceEpoch.toString();
}
```

**Comment by Vasantika20** [comment]
Okay...i got your point. But i have one more problem with this. i want to set seekbar for video recording & according to this code i have to set seekbar vertically. Then values on seekbar will not show properly. what to do?

**Comment by Vasantika20** [comment]
![Screenshot_2020-02-28-17-32-51-745_com example flutter_video_app](https://user-images.githubusercontent.com/52956589/75547351-ac21c800-5a50-11ea-9376-beaff0b54c0c.jpg)

I want to set this type of view in my screen, then there is a camera preview problem, Please help me if you have any idea to set this type of view.

**Comment by Jackiu1997** [comment]
you can use RotatedBox to rotate the preview widget, that is also ok.

**Comment by Vasantika20** [comment]
yes i tried with RotateBox also, but then view position & size  not set properly. Need to find another way. I think it should be done with camera preview only.

**Comment by Jackiu1997** [comment]
Did see the [camera pub example](https://pub.dev/packages/camera#-example-tab-),
this may be useful.

**Comment by Vasantika20** [comment]
Also tried this, it has same result.

**Comment by Jackiu1997** [comment]
I fixed DeviceOrientation.landscapeLeft, and set RotatedBox -1, it profermance good.

**Comment by Jackiu1997** [comment]
``` Dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:camera/camera.dart';
import 'package:path_provider/path_provider.dart';

import 'package:flutter_camera/tools/photo_tools.dart';
import 'package:flutter_camera/pages/album_page.dart';

/// 相机主页面
///
///   用于进行照相操作，采用 camera 获取相机流数据
///
class CameraPage extends StatefulWidget {
  final List<CameraDescription> cameras;

  CameraPage(this.cameras, {Key key}) : super(key: key);

  @override
  _CameraPageState createState() => _CameraPageState();
}

class _CameraPageState extends State<CameraPage> {
  CameraController controller;
  int nowCamera = 1;

  @override
  void initState() {
    super.initState();

    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeLeft
    ]);

    _onButtonChangeCameraPressed();
    checkNotInDBPhotos();
  }

  @override
  void dispose() {
    controller?.dispose();

    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight,
    ]);

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      child: Scaffold(
        body: Stack(
          alignment: Alignment.center,
          fit: StackFit.expand,
          children: <Widget>[
            Container(
              color: Colors.black,
              child: RotatedBox(
                quarterTurns: -1,
                child: _cameraPreViewWidget(),
              ),
            ),
            Positioned(
              bottom: 18.0,
              child: _bottomBarWidget(),
            ),
          ],
        ),
      ),
      onWillPop: () {
        SystemNavigator.pop();
      },
    );
  }

  Widget _buildPortraitScreen() {
    return Stack(
      alignment: Alignment.center,
      fit: StackFit.expand,
      children: <Widget>[
        Container(
          color: Colors.black,
          child: _cameraPreViewWidget(),
        ),
        Positioned(
          bottom: 18.0,
          child: _bottomBarWidget(),
        ),
      ],
    );
  }

  Widget _buildLandscapeScreen() {
    return Stack(
      alignment: Alignment.center,
      fit: StackFit.expand,
      children: <Widget>[
        Container(
          color: Colors.black,
          child: RotatedBox(
            quarterTurns: 1,
            child: _cameraPreViewWidget(),
          ),
        ),
        Positioned(
          right: 18.0,
          child: _bottomBarWidget(),
        ),
      ],
    );
  }

  /// 子 Widget 定义
  ///
  /// 相机预览 Widget
  Widget _cameraPreViewWidget() {
    return Center(
      child: !controller.value.isInitialized
          ? null
          : AspectRatio(
              aspectRatio: controller.value.aspectRatio,
              child: CameraPreview(controller),
            ),
    );
  }

  /// 页面底部按钮 Widget
  Widget _bottomBarWidget() {
    return SizedBox(
      width: 300,
      height: 90,
      child: Row(
        children: <Widget>[
          Expanded(
            flex: 1,
            child: FloatingActionButton(
              heroTag: "btn1",
              child: Icon(Icons.photo),
              backgroundColor: Color(0x50FFFFFF),
              onPressed: _onButtonOpenAlbumPressed,
            ),
          ),
          Expanded(
            flex: 1,
            child: FloatingActionButton(
              heroTag: "btn2",
              child: Icon(Icons.camera),
              backgroundColor: Color(0x50FFFFFF),
              onPressed: _onButtonTakePhotoPressed,
            ),
          ),
          Expanded(
            flex: 1,
            child: FloatingActionButton(
              heroTag: "btn3",
              child: nowCamera == 0
                  ? Icon(Icons.camera_rear)
                  : Icon(Icons.camera_front),
              backgroundColor: Color(0x50FFFFFF),
              onPressed: _onButtonChangeCameraPressed,
            ),
          ),
        ],
      ),
    );
  }

  /// 按钮事件响应
  ///
  /// 进入相册按钮响应
  void _onButtonOpenAlbumPressed() async {
    Navigator.push(
        context, MaterialPageRoute(builder: (context) => AlbumPage()));
  }

  /// 拍照按钮响应
  void _onButtonTakePhotoPressed() async {
    if (!controller.value.isInitialized) {
      return null;
    }
    final Directory extDir = await getApplicationDocumentsDirectory();
    final String dirPath = '${extDir.path}/Pictures';
    await Directory(dirPath).create(recursive: true);
    final String filePath = '$dirPath/IMG_${timestamp()}.jpg';

    if (controller.value.isTakingPicture) {
      return null;
    }
    await controller.takePicture(filePath);
    createPhotoData(filePath);
  }

  /// 转换摄像头按钮响应
  void _onButtonChangeCameraPressed() async {
    nowCamera = nowCamera == 0 ? 1 : 0;
    CameraDescription cameraDescription = widget.cameras[nowCamera];
    if (controller != null) {
      await controller.dispose();
    }
    controller = CameraController(cameraDescription, ResolutionPreset.high);
    controller.addListener(() {
      if (mounted) setState(() {});
    });
    await controller.initialize();
    if (mounted) setState(() {});
  }

  /// 生成当前时间戳，用作相片名称一部分
  String timestamp() => DateTime.now().millisecondsSinceEpoch.toString();
}

```

**Comment by Jackiu1997** [comment]
![Screenshot_2020-02-28-20-34-32-126_com example fl](https://user-images.githubusercontent.com/30568773/75549070-c2884d80-5a69-11ea-907f-a53a52294420.jpg)
this is 16/9 photo

**Comment by Jackiu1997** [comment]
this is 16/9 photo

**Comment by Vasantika20** [comment]
Its working. Thank you so much for your help.

**Comment by Jackiu1997** [comment]
Your are welcome, It is my pleasure to answer the problem.
